name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  models: read

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Diff
        id: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" > pr_details.json
          jq -r '.diff_url' pr_details.json > diff_url.txt
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "$(cat diff_url.txt)" > pr_diff.txt

      - name: AI Review via GitHub Models API
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          REVIEW=$(curl -s "https://models.github.ai/inference/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d '{
              "messages": [
                {"role": "system", "content": "Ты опытный Python code reviewer. Проведи ревью этого pull request diff на русском языке: укажи возможные баги, проблемы качества кода, дай советы по улучшению."},
                {"role": "user", "content": '"'"$(head -c 12000 pr_diff.txt | jq -Rs .)"'"'}
              ],
              "model": "openai/gpt-4o"
            }' | jq -r '.choices[0].message.content')
          echo "$REVIEW" > review.txt

      - name: Post Review as PR Comment
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          COMMENT=$(cat review.txt)
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"body\": \"$COMMENT\"}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"
